# Generated by Django 4.2.8 on 2026-01-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('self', 'Auto-aprovação'), ('manager', 'Aprovação Gestor')], max_length=20, verbose_name='Tipo de Aprovação')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('adjustments', 'Solicitar Ajustes'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Decisão')),
                ('decision_notes', models.TextField(blank=True, verbose_name='Observações da Decisão')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decidido em')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificação Enviada')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('has_attachment', models.BooleanField(default=False, verbose_name='Tem Anexo')),
                ('attachment_s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3 Anexo')),
                ('attachment_s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3 Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Comentário de Aprovação',
                'verbose_name_plural': 'Comentários de Aprovação',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='planning', max_length=20, verbose_name='Status')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Conteúdo do Projeto',
                'verbose_name_plural': 'Conteúdos dos Projetos',
                'ordering': ['-added_at'],
            },
        ),
    ]
