# Generated by Django 4.2.8 on 2026-01-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_projects', to='content.generatedcontent', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contents', to='campaigns.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='approvalcomment',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaigns.approval', verbose_name='Aprovação'),
        ),
        migrations.AddField(
            model_name='approvalcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
        migrations.AddField(
            model_name='approval',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content.generatedcontent', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='approval',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='campaigns.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='approval',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcontent',
            unique_together={('project', 'content')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='campaigns_p_created_027534_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['area', '-created_at'], name='campaigns_p_area_id_a1e4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='campaigns_p_status_cf9555_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalcomment',
            index=models.Index(fields=['approval', 'created_at'], name='campaigns_a_approva_679ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['-requested_at'], name='campaigns_a_request_17fde9_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'decision'], name='campaigns_a_approve_a54b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['decision'], name='campaigns_a_decisio_3997af_idx'),
        ),
    ]
