# Generated by Django 4.2.8 on 2026-01-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_videoavatar_videoavatarstatus_and_more'),
        ('core', '0002_organization_pautaauditlog_alter_area_name_and_more'),
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content.post', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_projects', to='content.post', verbose_name='Conteúdo'),
        ),
    ]
