# Generated by Django 4.2.8 on 2026-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_comparison_image_s3_key_and_more'),
        ('campaigns', '0003_project_organization_alter_approval_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='posts.post', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_projects', to='posts.post', verbose_name='Conteúdo'),
        ),
    ]
