# Generated by Django 4.2.8 on 2026-03-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_alter_knowledgebase_descricao_produto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typography',
            unique_together=set(),
        ),
    ]
