# Generated by Django 4.2.8 on 2026-04-15 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0019_remove_typography_unique_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_visual_spec',
            field=models.JSONField(blank=True, help_text='Especificação visual estruturada da marca (cores, tipografia, grid, grafismos)', null=True, verbose_name='Brand Visual Spec'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_visual_spec_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=10, null=True, verbose_name='Confiança do Brand Visual Spec'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_visual_spec_source',
            field=models.CharField(blank=True, choices=[('brandguide_pdf', 'Brandguide PDF'), ('reference_images', 'Imagens de Referência'), ('hybrid', 'Híbrido (PDF + Referências)'), ('manual', 'Preenchimento Manual')], max_length=30, null=True, verbose_name='Origem do Brand Visual Spec'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_visual_spec_validated',
            field=models.BooleanField(default=False, verbose_name='Brand Visual Spec validado pelo usuário'),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='aspects_to_use',
            field=models.JSONField(blank=True, default=list, help_text='Lista de flags: paleta_cor, mood, composicao, tipografia_aplicada, uso_fotografia, estilo_ilustracao, grafismos, tratamento_cor', verbose_name='Aspectos a aproveitar'),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='importance',
            field=models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10, verbose_name='Importância'),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='usage_description',
            field=models.TextField(blank=True, help_text='Descrição livre do que o usuário considera importante', verbose_name='O que aproveitar desta imagem'),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='usage_type',
            field=models.CharField(choices=[('inspire', 'Inspirar (referência geral)'), ('mimic', 'Seguir fielmente o estilo'), ('avoid', 'EVITAR (não quero parecer com isso)')], default='inspire', max_length=10, verbose_name='Tipo de uso'),
        ),
        migrations.CreateModel(
            name='BrandguideUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome original do arquivo')),
                ('s3_key_pdf', models.CharField(max_length=500, verbose_name='Chave S3 do PDF')),
                ('s3_url_pdf', models.URLField(max_length=1000, verbose_name='URL S3 do PDF')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='Total de páginas')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('processing_status', models.CharField(choices=[('uploaded', 'Enviado'), ('converting', 'Convertendo PDF'), ('extracting_assets', 'Extraindo assets'), ('analyzing', 'Analisando com IA'), ('completed', 'Concluído'), ('error', 'Erro')], default='uploaded', max_length=20, verbose_name='Status do processamento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandguide_uploads', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandguide_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Upload de Brandguide',
                'verbose_name_plural': 'Uploads de Brandguides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandguidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Número da página')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3 do PNG')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3 do PNG')),
                ('width', models.PositiveIntegerField(verbose_name='Largura (px)')),
                ('height', models.PositiveIntegerField(verbose_name='Altura (px)')),
                ('extracted_text', models.TextField(blank=True, help_text='Texto da página extraído por pdfplumber', verbose_name='Texto extraído')),
                ('category', models.CharField(choices=[('capa', 'Capa'), ('indice', 'Índice'), ('logotipo', 'Logotipo'), ('tipografia', 'Tipografia'), ('cores', 'Cores'), ('grafismo', 'Grafismo'), ('grid', 'Grid'), ('aplicacoes', 'Aplicações'), ('informacional', 'Informacional'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Categoria')),
                ('relevance', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10, verbose_name='Relevância')),
                ('brandguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.brandguideupload', verbose_name='Brandguide')),
            ],
            options={
                'verbose_name': 'Página de Brandguide',
                'verbose_name_plural': 'Páginas de Brandguides',
                'ordering': ['brandguide', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='BrandgraficModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: "Módulo vertical 03"', max_length=100, verbose_name='Nome')),
                ('extraction_type', models.CharField(choices=[('vector_embedded', 'Vetor embutido (SVG)'), ('image_embedded', 'Imagem embutida (PNG/JPG)'), ('cropped_from_page', 'Recortado da página')], max_length=30, verbose_name='Tipo de extração')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página de origem')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('file_format', models.CharField(choices=[('svg', 'SVG'), ('png', 'PNG')], max_length=10, verbose_name='Formato')),
                ('has_transparency', models.BooleanField(default=False, verbose_name='Tem transparência')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Largura')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Altura')),
                ('orientation', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('both', 'Ambos')], default='both', max_length=20, verbose_name='Orientação')),
                ('usage_hint', models.CharField(blank=True, max_length=255, verbose_name='Sugestão de uso')),
                ('approved_by_user', models.BooleanField(default=False, verbose_name='Aprovado pelo usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('brandguide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafic_modules', to='knowledge.brandguideupload', verbose_name='Brandguide de origem')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grafic_modules', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
            ],
            options={
                'verbose_name': 'Módulo de Grafismo',
                'verbose_name_plural': 'Módulos de Grafismos',
                'ordering': ['knowledge_base', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='brandguideupload',
            index=models.Index(fields=['knowledge_base', '-created_at'], name='knowledge_b_knowled_d3e6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='brandguideupload',
            index=models.Index(fields=['processing_status'], name='knowledge_b_process_55404a_idx'),
        ),
        migrations.AddIndex(
            model_name='brandguidepage',
            index=models.Index(fields=['brandguide', 'page_number'], name='knowledge_b_brandgu_92547e_idx'),
        ),
        migrations.AddIndex(
            model_name='brandguidepage',
            index=models.Index(fields=['category', 'relevance'], name='knowledge_b_categor_f31c15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brandguidepage',
            unique_together={('brandguide', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='brandgraficmodule',
            index=models.Index(fields=['knowledge_base', 'is_active', 'approved_by_user'], name='knowledge_b_knowled_b878b2_idx'),
        ),
    ]
