# Generated by Django 4.2.8 on 2026-04-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0020_knowledgebase_brand_visual_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandguideupload',
            name='ai_usage',
            field=models.JSONField(blank=True, help_text='Tokens consumidos e custo estimado por etapa (triagem + analise)', null=True, verbose_name='Uso de tokens da IA'),
        ),
    ]
