# Generated by Django 4.2.8 on 2026-04-16 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0021_brandguideupload_ai_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandgraficmodule',
            name='extraction_type',
            field=models.CharField(choices=[('vector_embedded', 'Vetor embutido (SVG)'), ('image_embedded', 'Imagem embutida (PNG/JPG)'), ('cropped_from_page', 'Recortado da página'), ('manual_upload', 'Upload manual')], max_length=30, verbose_name='Tipo de extração'),
        ),
        migrations.CreateModel(
            name='VisualTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: "Feed evento 2x3", "Story institucional"', max_length=200, verbose_name='Nome')),
                ('template_type', models.CharField(choices=[('feed', 'Feed'), ('story', 'Story'), ('quadrado', 'Quadrado'), ('carrossel_slide', 'Slide de Carrossel'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de template')),
                ('social_network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('universal', 'Universal')], default='universal', max_length=20, verbose_name='Rede social')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Largura')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Altura')),
                ('source', models.CharField(choices=[('manual_upload', 'Upload manual'), ('pdf_extracted', 'Extraído do PDF')], max_length=20, verbose_name='Origem')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página de origem no PDF')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('approved_by_user', models.BooleanField(default=False, verbose_name='Aprovado pelo usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('assets', models.ManyToManyField(blank=True, help_text='Grafismos/assets usados neste template', related_name='templates', to='knowledge.brandgraficmodule', verbose_name='Assets vinculados')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_templates', to='knowledge.knowledgebase', verbose_name='Base de Conhecimento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_templates_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Template Visual',
                'verbose_name_plural': 'Templates Visuais',
                'ordering': ['knowledge_base', 'template_type', 'name'],
                'indexes': [models.Index(fields=['knowledge_base', 'is_active', 'approved_by_user'], name='knowledge_v_knowled_1838c0_idx'), models.Index(fields=['template_type', 'social_network'], name='knowledge_v_templat_081fa6_idx')],
            },
        ),
    ]
