# Generated by Django 4.2.8 on 2026-04-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0022_visual_template_and_manual_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='created_from_brandguide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_colors', to='knowledge.brandguideupload', verbose_name='Criado pelo brandguide'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='brandguide_filled_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos preenchidos pelo brandguide'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='logo_usage_notes',
            field=models.TextField(blank=True, default='', help_text='Variações, área de segurança, reduções mínimas e outras orientações', verbose_name='Notas de uso do logo'),
        ),
        migrations.AddField(
            model_name='typography',
            name='created_from_brandguide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_typography', to='knowledge.brandguideupload', verbose_name='Criado pelo brandguide'),
        ),
    ]
