# Generated by Django 4.2.8 on 2026-05-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0023_add_brandguide_apply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_layout_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Cache do layout analisado das references via Claude Vision', verbose_name='Spec de layout da marca'),
        ),
    ]
