# Generated by Django 4.2.8 on 2026-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0023_add_brandguide_apply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='brand_visual_spec_v1_backup',
            field=models.JSONField(blank=True, help_text='Snapshot do brand_visual_spec antes da migracao para v2 estrutural', null=True, verbose_name='Backup do Brand Visual Spec v1 (pre-Compose Engine)'),
        ),
        migrations.AddField(
            model_name='visualtemplate',
            name='aspect_ratio',
            field=models.CharField(blank=True, help_text='Ex: 1:1, 4:5, 9:16, 16:9, produto_fisico', max_length=20, verbose_name='Aspect ratio'),
        ),
        migrations.AddField(
            model_name='visualtemplate',
            name='template_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Slots com bbox, tipo, tokens para Compose Engine', verbose_name='Spec estrutural do template'),
        ),
    ]
