# Generated by Django 4.2.8 on 2026-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0025_referenceimage_analysis_cost_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandgraficmodule',
            name='analysis_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo da análise (USD)'),
        ),
        migrations.AddField(
            model_name='brandgraficmodule',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status da análise visual'),
        ),
        migrations.AddField(
            model_name='brandgraficmodule',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analisada em'),
        ),
        migrations.AddField(
            model_name='brandgraficmodule',
            name='visual_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Análise objetiva do grafismo (tipo, cores, aplicação) gerada via IA', verbose_name='Dossiê visual'),
        ),
    ]
