# Generated by Django 4.2.8 on 2026-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0025_alter_visualtemplate_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualtemplate',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='', help_text='Ex: 1:1, 4:5, 9:16, 16:9, produto_fisico, produto_fisico_cilindrico', max_length=50, verbose_name='Aspect ratio'),
        ),
    ]
