# Generated by Django 4.2.8 on 2026-01-12 23:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('asset_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=20, verbose_name='Tipo')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(max_length=1000, verbose_name='URL S3')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho (bytes)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_started_at', models.DateTimeField(verbose_name='Criação Iniciada em')),
                ('creation_completed_at', models.DateTimeField(verbose_name='Criação Concluída em')),
                ('creation_duration_seconds', models.IntegerField(verbose_name='Duração Criação (s)')),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado para Aprovação em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('approval_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duração Aprovação (s)')),
                ('adjustment_count', models.IntegerField(default=0, verbose_name='Quantidade de Ajustes')),
                ('total_adjustment_time_seconds', models.IntegerField(default=0, verbose_name='Tempo Total de Ajustes (s)')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Total (USD)')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Tokens Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Métrica de Conteúdo',
                'verbose_name_plural': 'Métricas de Conteúdo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('carrossel', 'Carrossel'), ('story', 'Story'), ('reels', 'Reels')], max_length=20, verbose_name='Tipo')),
                ('social_network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Rede Social')),
                ('ia_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='Provider IA')),
                ('ia_model_text', models.CharField(max_length=50, verbose_name='Modelo IA Texto')),
                ('ia_model_image', models.CharField(blank=True, max_length=50, verbose_name='Modelo IA Imagem')),
                ('caption', models.TextField(verbose_name='Legenda')),
                ('hashtags', models.JSONField(default=list, verbose_name='Hashtags')),
                ('has_image', models.BooleanField(default=False, verbose_name='Tem Imagem')),
                ('image_s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3 Imagem')),
                ('image_s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3 Imagem')),
                ('image_prompt', models.TextField(blank=True, verbose_name='Prompt da Imagem')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('awaiting_approval', 'Aguardando Aprovação'), ('in_adjustment', 'Em Ajuste'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conteúdo Gerado',
                'verbose_name_plural': 'Conteúdos Gerados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IAModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('perplexity', 'Perplexity')], max_length=20, verbose_name='Provider')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('operation', models.CharField(choices=[('pauta', 'Geração de Pauta'), ('post_text', 'Geração de Texto'), ('post_image', 'Geração de Imagem'), ('trend_analysis', 'Análise de Trend'), ('web_research', 'Pesquisa Web')], max_length=50, verbose_name='Operação')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='Tokens Input')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='Tokens Output')),
                ('tokens_total', models.IntegerField(default=0, verbose_name='Tokens Total')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='Custo (USD)')),
                ('execution_time_seconds', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Tempo de Execução (s)')),
                ('started_at', models.DateTimeField(verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(verbose_name='Concluído em')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('timeout', 'Timeout')], max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Uso de Modelo IA',
                'verbose_name_plural': 'Usos de Modelos IA',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500, verbose_name='Tema')),
                ('target_audience', models.CharField(max_length=200, verbose_name='Público-alvo')),
                ('objective', models.CharField(choices=[('engajamento', 'Engajamento'), ('conversao', 'Conversão'), ('educacao', 'Educação'), ('branding', 'Branding'), ('vendas', 'Vendas')], max_length=100, verbose_name='Objetivo')),
                ('additional_context', models.TextField(blank=True, verbose_name='Contexto Adicional')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('key_points', models.JSONField(default=list, help_text='Lista de pontos principais', verbose_name='Pontos-chave')),
                ('suggested_formats', models.JSONField(default=list, help_text='["post", "carrossel", "video", etc]', verbose_name='Formatos Sugeridos')),
                ('research_sources', models.JSONField(blank=True, default=list, help_text='URLs e referências usadas', verbose_name='Fontes de Pesquisa')),
                ('trends_related', models.JSONField(blank=True, default=list, verbose_name='Trends Relacionadas')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluída'), ('error', 'Erro')], default='processing', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Palavra-chave')),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends'), ('reddit', 'Reddit'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=50, verbose_name='Fonte')),
                ('trend_score', models.IntegerField(help_text='0-100', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score')),
                ('volume', models.BigIntegerField(blank=True, help_text='Volume de buscas/menções', null=True, verbose_name='Volume')),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Crescimento (%)')),
                ('relevance', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=20, verbose_name='Relevância')),
                ('ia_analysis', models.TextField(verbose_name='Análise IA')),
                ('suggested_actions', models.JSONField(default=list, verbose_name='Ações Sugeridas')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos')),
                ('related_topics', models.JSONField(blank=True, default=list, verbose_name='Tópicos Relacionados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerta Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Trend Monitor',
                'verbose_name_plural': 'Trends Monitoradas',
                'ordering': ['-trend_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Query')),
                ('search_type', models.CharField(choices=[('topic', 'Tópico Geral'), ('competitor', 'Concorrente'), ('trend', 'Trend')], max_length=20, verbose_name='Tipo de Pesquisa')),
                ('urls_scraped', models.JSONField(default=list, verbose_name='URLs Pesquisadas')),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('key_insights', models.JSONField(default=list, verbose_name='Insights Principais')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendações')),
                ('raw_content', models.TextField(blank=True, verbose_name='Conteúdo Bruto')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro')], default='processing', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
            ],
            options={
                'verbose_name': 'Web Insight',
                'verbose_name_plural': 'Web Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
