# Generated by Django 4.2.8 on 2026-01-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinsight',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_insights', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='webinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_insights', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='trendmonitor',
            index=models.Index(fields=['-created_at'], name='content_tre_created_50da70_idx'),
        ),
        migrations.AddIndex(
            model_name='trendmonitor',
            index=models.Index(fields=['keyword'], name='content_tre_keyword_178552_idx'),
        ),
        migrations.AddIndex(
            model_name='trendmonitor',
            index=models.Index(fields=['relevance'], name='content_tre_relevan_4c5469_idx'),
        ),
        migrations.AddIndex(
            model_name='trendmonitor',
            index=models.Index(fields=['-trend_score'], name='content_tre_trend_s_d1f323_idx'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='iamodelusage',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_usages', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='iamodelusage',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_usages', to='content.generatedcontent', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='iamodelusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_usages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content.pauta', verbose_name='Pauta'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='contentmetrics',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='content.generatedcontent', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='asset',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='webinsight',
            index=models.Index(fields=['-created_at'], name='content_web_created_3f4cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='webinsight',
            index=models.Index(fields=['user', '-created_at'], name='content_web_user_id_a4d659_idx'),
        ),
        migrations.AddIndex(
            model_name='webinsight',
            index=models.Index(fields=['status'], name='content_web_status_69a2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['-created_at'], name='content_pau_created_debbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['user', '-created_at'], name='content_pau_user_id_627ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['area', '-created_at'], name='content_pau_area_id_f9aab3_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['status'], name='content_pau_status_ccdd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='iamodelusage',
            index=models.Index(fields=['-started_at'], name='content_iam_started_8b1dab_idx'),
        ),
        migrations.AddIndex(
            model_name='iamodelusage',
            index=models.Index(fields=['area', '-started_at'], name='content_iam_area_id_3cd905_idx'),
        ),
        migrations.AddIndex(
            model_name='iamodelusage',
            index=models.Index(fields=['provider', '-started_at'], name='content_iam_provide_9ec9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='iamodelusage',
            index=models.Index(fields=['operation'], name='content_iam_operati_0e7fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['-created_at'], name='content_gen_created_27de35_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['user', '-created_at'], name='content_gen_user_id_9f619b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['area', '-created_at'], name='content_gen_area_id_ebd159_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['status'], name='content_gen_status_7606e9_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['social_network'], name='content_gen_social__6aede4_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-created_at'], name='content_ass_created_d407ea_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['area', '-created_at'], name='content_ass_area_id_58d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='content_ass_asset_t_12eac7_idx'),
        ),
    ]
