# Generated by Django 4.2.8 on 2026-01-21 00:34

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_theme', models.TextField(blank=True, help_text='Tema solicitado pelo usuário para geração do post', verbose_name='Tema Solicitado')),
                ('title', models.CharField(blank=True, help_text='Título do post (se aplicável)', max_length=220, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo do post (se aplicável)', max_length=220, verbose_name='Subtítulo')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('carrossel', 'Carrossel'), ('story', 'Story'), ('reels', 'Reels')], max_length=20, verbose_name='Tipo')),
                ('social_network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Rede Social')),
                ('ia_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='Provider IA')),
                ('ia_model_text', models.CharField(max_length=50, verbose_name='Modelo IA Texto')),
                ('ia_model_image', models.CharField(blank=True, max_length=50, verbose_name='Modelo IA Imagem')),
                ('caption', models.TextField(verbose_name='Legenda')),
                ('hashtags', models.JSONField(default=list, verbose_name='Hashtags')),
                ('cta', models.CharField(blank=True, help_text='Call-to-action do post', max_length=160, verbose_name='CTA')),
                ('cta_requested', models.BooleanField(default=True, help_text='Usuário quer CTA no post', verbose_name='CTA Solicitado')),
                ('formats', models.JSONField(blank=True, default=list, help_text='Lista de formatos: ["feed", "story", "reels"]', verbose_name='Formatos')),
                ('is_carousel', models.BooleanField(default=False, help_text='Post é um carrossel (múltiplas imagens)', verbose_name='É Carrossel')),
                ('image_count', models.PositiveSmallIntegerField(default=1, help_text='Número de imagens no carrossel', verbose_name='Quantidade de Imagens')),
                ('slides_metadata', models.JSONField(blank=True, default=list, help_text='Dados estruturados de cada slide do carrossel', verbose_name='Metadados dos Slides')),
                ('revisions_remaining', models.PositiveSmallIntegerField(default=2, help_text='Número de revisões que o usuário ainda pode solicitar', verbose_name='Revisões Restantes')),
                ('thread_id', models.CharField(blank=True, help_text='ID do thread/job de processamento (N8N, GPT, etc)', max_length=160, verbose_name='Thread ID')),
                ('has_image', models.BooleanField(default=False, verbose_name='Tem Imagem')),
                ('image_s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3 Imagem')),
                ('image_s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3 Imagem')),
                ('image_prompt', models.TextField(blank=True, verbose_name='Prompt da Imagem')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('awaiting_approval', 'Aguardando Aprovação'), ('in_adjustment', 'Em Ajuste'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(help_text='Imagem do avatar/personagem (foto/ilustração)', storage=apps.core.storage.AvatarImageStorage(), upload_to='%Y/%m/%d/', verbose_name='Imagem do Avatar')),
                ('script_text', models.TextField(help_text='Texto para locução/legenda do vídeo (máx 500 caracteres)', max_length=500, verbose_name='Texto do Script')),
                ('avatar_action', models.CharField(blank=True, help_text="Ação desejada: 'acenar', 'sorrir', 'olhar para câmera', etc.", max_length=200, verbose_name='Ação do Avatar')),
                ('video_file', models.FileField(blank=True, help_text='Vídeo final gerado (MP4)', null=True, storage=apps.core.storage.VideoAvatarStorage(), upload_to='%Y/%m/%d/', verbose_name='Arquivo de Vídeo')),
                ('video_duration', models.FloatField(default=0, help_text='Duração do vídeo em segundos', verbose_name='Duração do Vídeo')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Thumbnail do vídeo (gerado automaticamente)', null=True, storage=apps.core.storage.VideoThumbnailStorage(), upload_to='%Y/%m/%d/', verbose_name='Thumbnail do Vídeo')),
                ('revisions_remaining', models.PositiveSmallIntegerField(default=1, help_text='Revisões restantes (padrão: 1)', verbose_name='Revisões Restantes')),
                ('expected_delivery_at', models.DateTimeField(blank=True, help_text='Prazo estimado de entrega (48h úteis)', null=True, verbose_name='Entrega Esperada em')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Data/hora em que vídeo foi entregue ao cliente', null=True, verbose_name='Entregue em')),
                ('thread_id', models.CharField(blank=True, help_text='ID do job de processamento (se aplicável)', max_length=160, verbose_name='Thread ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vídeo Avatar',
                'verbose_name_plural': 'Vídeos Avatar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAvatarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Status de Vídeo Avatar',
                'verbose_name_plural': 'Status de Vídeos Avatar',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='area',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='pauta',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='user',
        ),
    ]
