# Generated by Django 4.2.8 on 2026-01-21 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_project_organization_alter_approval_content_and_more'),
        ('content', '0003_post_videoavatar_videoavatarstatus_and_more'),
        ('core', '0002_organization_pautaauditlog_alter_area_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='iamodelusage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_usages', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual esta pauta pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='trendmonitor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_monitors', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='webinsight',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_insights', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='is_revision_of',
            field=models.ForeignKey(blank=True, help_text='Se for revisão, aponta para o vídeo original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='content.videoavatar', verbose_name='Revisão de'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_avatar', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='content.videoavatarstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual este post pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='post',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.pauta', verbose_name='Pauta'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='contentmetrics',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='content.post', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='iamodelusage',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_usages', to='content.post', verbose_name='Conteúdo'),
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='content_pos_created_415459_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='content_pos_user_id_79b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['area', '-created_at'], name='content_pos_area_id_bf09bf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='content_pos_status_94dfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['social_network'], name='content_pos_social__ea571b_idx'),
        ),
    ]
