# Generated by Django 4.2.8 on 2026-01-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_asset_organization_iamodelusage_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendmonitor',
            options={'ordering': ['-trend_score', '-created_at'], 'verbose_name': 'Trend Monitor', 'verbose_name_plural': 'Trend Monitors'},
        ),
        migrations.AlterField(
            model_name='pauta',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pontos principais', verbose_name='Pontos-chave'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='suggested_formats',
            field=models.JSONField(blank=True, default=list, help_text='["post", "carrossel", "video", etc]', verbose_name='Formatos Sugeridos'),
        ),
    ]
