# Generated by Django 4.2.8 on 2026-07-27 19:41

import apps.core.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # NOTA: migration EDITADA À MÃO após makemigrations — removidos o
    # DeleteModel('Post') e os AlterField de contentmetrics/iamodelusage,
    # que são drift antigo do estado de migrations (Post movido p/ app posts)
    # e NÃO fazem parte desta feature. Não reintroduzir sem plano próprio.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_organization_archetype_two_step'),
        ('content', '0005_pauta_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeygenAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome de exibição para o cliente (ex.: "Apresentadora Ana")', max_length=120, verbose_name='Nome')),
                ('look_id', models.CharField(help_text='ID do LOOK na HeyGen (não o ID do grupo) — GET /v3/avatars/looks', max_length=64, verbose_name='Look ID (HeyGen)')),
                ('voice_id', models.CharField(help_text='Voz pt-BR da HeyGen usada com este avatar — GET /v3/voices', max_length=64, verbose_name='Voice ID (HeyGen)')),
                ('engine', models.CharField(choices=[('avatar_iv', 'Avatar IV'), ('avatar_v', 'Avatar V')], default='avatar_iv', help_text='Confirmar em supported_api_engines do look antes de usar avatar_v', max_length=16, verbose_name='Engine')),
                ('preview_image', models.ImageField(blank=True, help_text='Foto do avatar exibida no seletor do formulário', null=True, storage=apps.core.storage.AvatarImageStorage(), upload_to='heygen/%Y/%m/', verbose_name='Imagem de Preview')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Pré-selecionado no formulário quando a org tem mais de um', verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heygen_avatars', to='core.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Avatar HeyGen',
                'verbose_name_plural': 'Avatares HeyGen',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeygenWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True, verbose_name='Event ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Evento de Webhook HeyGen',
                'verbose_name_plural': 'Eventos de Webhook HeyGen',
            },
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Custo real (duração × tarifa/s), fechado no webhook', max_digits=10, verbose_name='Custo (USD)'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que solicitou o vídeo (recebe os emails)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_avatar', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='error_code',
            field=models.CharField(blank=True, help_text='Código de erro da HeyGen quando status=failed', max_length=64, verbose_name='Código de Erro'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='estimated_duration',
            field=models.FloatField(default=0, help_text='Duração estimada pelo roteiro (s) antes do render; a real fica em video_duration', verbose_name='Duração Estimada'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='heygen_video_id',
            field=models.CharField(blank=True, db_index=True, help_text='video_id retornado pelo POST /v3/videos', max_length=64, verbose_name='Video ID (HeyGen)'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Idempotency-Key enviada à HeyGen (uuid5 determinístico) — retry do Celery nunca gera vídeo cobrado em dobro', max_length=64, null=True, unique=True, verbose_name='Idempotency Key'),
        ),
        migrations.AlterField(
            model_name='videoavatar',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Legado (fluxo manual): imagem enviada pelo cliente', null=True, storage=apps.core.storage.AvatarImageStorage(), upload_to='%Y/%m/%d/', verbose_name='Imagem do Avatar'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='Avatar do catálogo da org escolhido pelo cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.heygenavatar', verbose_name='Avatar HeyGen'),
        ),
        migrations.AddConstraint(
            model_name='heygenavatar',
            constraint=models.UniqueConstraint(fields=('organization', 'look_id'), name='uniq_heygen_avatar_org_look'),
        ),
    ]
