# Generated by Django 4.2.8 on 2026-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_comparison_image_s3_key_and_more'),
        ('campaigns', '0004_alter_approval_content_alter_projectcontent_content'),
        ('content', '0005_pauta_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmetrics',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='posts.post', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='iamodelusage',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_usages', to='posts.post', verbose_name='Conteúdo'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
