# Generated by Django 4.2.8 on 2026-07-27 23:43

import apps.core.storage
from django.db import migrations, models
import django.db.models.deletion


def move_looks_forward(apps, schema_editor):
    """Cada HeygenAvatar antigo (que era 1 look) vira apresentador + 1 HeygenLook."""
    HeygenAvatar = apps.get_model('content', 'HeygenAvatar')
    HeygenLook = apps.get_model('content', 'HeygenLook')
    VideoAvatar = apps.get_model('content', 'VideoAvatar')

    for avatar in HeygenAvatar.objects.all():
        look = HeygenLook.objects.create(
            avatar=avatar,
            look_id=avatar.look_id,
            name=avatar.name,
            preview_image=avatar.preview_image.name if avatar.preview_image else None,
            is_active=avatar.is_active,
            is_default=True,
        )
        VideoAvatar.objects.filter(avatar=avatar).update(look=look)


def move_looks_backward(apps, schema_editor):
    """Reverso: devolve o look padrão para os campos do HeygenAvatar."""
    HeygenAvatar = apps.get_model('content', 'HeygenAvatar')
    for avatar in HeygenAvatar.objects.all():
        look = avatar.looks.order_by('-is_default', 'id').first()
        if look:
            avatar.look_id = look.look_id
            avatar.preview_image = look.preview_image.name if look.preview_image else None
            avatar.save()


class Migration(migrations.Migration):

    # NOTA: migration EDITADA À MÃO após makemigrations — removidos o
    # DeleteModel('Post'), os RemoveField de post.* e os AlterField de
    # contentmetrics/iamodelusage (drift antigo do estado de migrations,
    # não fazem parte desta feature) e ADICIONADA a data migration que
    # converte o catálogo antigo (1 avatar = 1 look) para o novo
    # (apresentador → looks). Não reintroduzir o drift sem plano próprio.
    dependencies = [
        ('content', '0006_heygenavatar_heygenwebhookevent_videoavatar_cost_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeygenLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_id', models.CharField(help_text='ID do LOOK na HeyGen (vai no payload do vídeo)', max_length=64, verbose_name='Look ID (HeyGen)')),
                ('name', models.CharField(help_text='Nome de exibição (ex.: "Escritório", "Casual")', max_length=160, verbose_name='Nome')),
                ('avatar_type', models.CharField(blank=True, help_text='photo_avatar | digital_twin (informativo, vem do sync)', max_length=24, verbose_name='Tipo')),
                ('preview_image', models.ImageField(blank=True, help_text='Foto exibida no card do formulário (o sync baixa da HeyGen)', null=True, storage=apps.core.storage.AvatarImageStorage(), upload_to='heygen/%Y/%m/', verbose_name='Imagem de Preview')),
                ('is_active', models.BooleanField(default=False, help_text='Só looks ativos aparecem para o cliente (curadoria da equipe)', verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Pré-selecionado no formulário', verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Look HeyGen',
                'verbose_name_plural': 'Looks HeyGen',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='heygenlook',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='content.heygenavatar', verbose_name='Apresentador'),
        ),
        migrations.AddField(
            model_name='heygenavatar',
            name='group_id',
            field=models.CharField(blank=True, help_text='ID do avatar GROUP na HeyGen — permite sincronizar os looks automaticamente (GET /v3/avatars/looks?group_id=...)', max_length=64, verbose_name='Group ID (HeyGen)'),
        ),
        migrations.AddField(
            model_name='videoavatar',
            name='look',
            field=models.ForeignKey(blank=True, help_text='Look (visual) escolhido — é o avatar_id enviado à HeyGen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.heygenlook', verbose_name='Look HeyGen'),
        ),
        migrations.RunPython(move_looks_forward, move_looks_backward),
        migrations.AlterModelOptions(
            name='heygenavatar',
            options={'ordering': ['name'], 'verbose_name': 'Apresentador HeyGen', 'verbose_name_plural': 'Apresentadores HeyGen'},
        ),
        migrations.RemoveConstraint(
            model_name='heygenavatar',
            name='uniq_heygen_avatar_org_look',
        ),
        migrations.RemoveField(
            model_name='heygenavatar',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='heygenavatar',
            name='look_id',
        ),
        migrations.RemoveField(
            model_name='heygenavatar',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='heygenavatar',
            name='engine',
            field=models.CharField(choices=[('avatar_iv', 'Avatar IV'), ('avatar_v', 'Avatar V')], default='avatar_iv', help_text='Confirmar em supported_api_engines dos looks antes de usar avatar_v', max_length=16, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='heygenavatar',
            name='name',
            field=models.CharField(help_text='Nome de exibição para o cliente (ex.: "Mauricio")', max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='heygenavatar',
            name='voice_id',
            field=models.CharField(help_text='Voz pt-BR da HeyGen usada com este apresentador — GET /v3/voices', max_length=64, verbose_name='Voice ID (HeyGen)'),
        ),
        migrations.AlterField(
            model_name='videoavatar',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='Apresentador do catálogo da org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.heygenavatar', verbose_name='Apresentador HeyGen'),
        ),
        migrations.AddConstraint(
            model_name='heygenavatar',
            constraint=models.UniqueConstraint(condition=models.Q(('group_id', ''), _negated=True), fields=('organization', 'group_id'), name='uniq_heygen_avatar_org_group'),
        ),
        migrations.AddConstraint(
            model_name='heygenlook',
            constraint=models.UniqueConstraint(fields=('avatar', 'look_id'), name='uniq_heygen_look_avatar_look'),
        ),
    ]
