# Generated by Django 4.2.8 on 2026-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Faça upload da imagem aqui. Será automaticamente enviada para S3.', null=True, upload_to='temp/posts/', verbose_name='Upload de Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='social_network',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Rede Social'),
        ),
    ]
