# Generated by Django 4.2.8 on 2026-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image_file_alter_post_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_images',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos com s3_key, s3_url, width, height de cada imagem gerada', verbose_name='Imagens Geradas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chave S3 Imagem (Principal)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_s3_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL S3 Imagem (Principal)'),
        ),
    ]
