# Generated by Django 4.2.8 on 2026-02-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_generated_images_alter_post_image_s3_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, help_text='Faça upload da imagem. Será automaticamente enviada para S3.', null=True, upload_to='temp/posts/', verbose_name='Upload de Imagem')),
                ('s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Imagem do Post',
                'verbose_name_plural': 'Imagens do Post',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
