# Generated by Django 4.2.8 on 2026-02-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('generating', 'Gerando'), ('image_generating', 'Gerando Imagem'), ('pending', 'Pendente de Aprovação'), ('in_adjustment', 'Em Ajuste'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PostChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensagem de solicitação de alteração', verbose_name='Mensagem')),
                ('requester_name', models.CharField(blank=True, max_length=160, verbose_name='Nome do Solicitante')),
                ('requester_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Solicitante')),
                ('change_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem')], default='text', max_length=10, verbose_name='Tipo de Alteração')),
                ('is_initial', models.BooleanField(default=False, help_text='True se é a primeira solicitação (sem mensagem customizada)', verbose_name='É Solicitação Inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração',
                'verbose_name_plural': 'Solicitações de Alteração',
                'ordering': ['-created_at'],
            },
        ),
    ]
