# Generated by Django 4.2.8 on 2026-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_status_postchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('generating', 'Agente Gerando Conteúdo'), ('image_generating', 'Agente Gerando Imagem'), ('image_ready', 'Imagem Disponível'), ('approved', 'Aprovado'), ('agent', 'Agente Alterando — Aguarde'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
