# Generated by Django 4.2.7 on 2026-03-01 23:21

from django.db import migrations


def populate_post_formats(apps, schema_editor):
    """
    Popula a tabela PostFormat com os 14 formatos padrão
    Baseado no documento FLUXO_GERAR_IMAGEM.md
    """
    PostFormat = apps.get_model('posts', 'PostFormat')
    
    formats = [
        # Instagram
        {'social_network': 'instagram', 'name': 'Feed Retrato', 'width': 1080, 'height': 1350, 'aspect_ratio': '4:5', 'order': 1},
        {'social_network': 'instagram', 'name': 'Feed Quadrado', 'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'order': 2},
        {'social_network': 'instagram', 'name': 'Feed Paisagem', 'width': 1080, 'height': 566, 'aspect_ratio': '1.91:1', 'order': 3},
        {'social_network': 'instagram', 'name': 'Stories', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 4},
        {'social_network': 'instagram', 'name': 'Reels', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 5},
        
        # Facebook
        {'social_network': 'facebook', 'name': 'Feed', 'width': 1200, 'height': 630, 'aspect_ratio': '16:9', 'order': 1},
        {'social_network': 'facebook', 'name': 'Feed Quadrado', 'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'order': 2},
        {'social_network': 'facebook', 'name': 'Stories', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 3},
        
        # LinkedIn
        {'social_network': 'linkedin', 'name': 'Feed', 'width': 1200, 'height': 627, 'aspect_ratio': '16:9', 'order': 1},
        {'social_network': 'linkedin', 'name': 'Feed Quadrado', 'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'order': 2},
        {'social_network': 'linkedin', 'name': 'Stories', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 3},
        
        # TikTok
        {'social_network': 'tiktok', 'name': 'Vídeo/Reels', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 1},
        
        # WhatsApp
        {'social_network': 'whatsapp', 'name': 'Status', 'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'order': 1},
        {'social_network': 'whatsapp', 'name': 'Imagem', 'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'order': 2},
    ]
    
    for fmt in formats:
        PostFormat.objects.create(**fmt)


def reverse_populate(apps, schema_editor):
    """Remove todos os formatos criados"""
    PostFormat = apps.get_model('posts', 'PostFormat')
    PostFormat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_add_postformat_model'),
    ]

    operations = [
        migrations.RunPython(populate_post_formats, reverse_populate),
    ]
