# Generated by Django 4.2.8 on 2026-03-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_populate_postformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(blank=True, max_length=500, verbose_name='Chave S3')),
                ('s3_url', models.URLField(blank=True, max_length=1000, verbose_name='URL S3')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Original')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_image_files', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Imagem de Referência do Post',
                'verbose_name_plural': 'Imagens de Referência do Post',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
