# Generated by Django 4.2.8 on 2026-04-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postreferenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comparison_image_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chave S3 da imagem de comparação'),
        ),
        migrations.AddField(
            model_name='post',
            name='comparison_image_s3_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL S3 da imagem de comparação'),
        ),
        migrations.AddField(
            model_name='post',
            name='generation_method',
            field=models.CharField(choices=[('free_style', 'Estilo livre (Gemini completo)'), ('controlled_render', 'Renderização controlada'), ('both', 'Comparar os dois')], default='free_style', max_length=30, verbose_name='Método de geração'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_brief',
            field=models.TextField(blank=True, verbose_name='Briefing da imagem'),
        ),
        migrations.AddField(
            model_name='post',
            name='layout_plan',
            field=models.JSONField(blank=True, help_text='JSON com áreas, restrições e template escolhido pela IA', null=True, verbose_name='Plano de Layout'),
        ),
        migrations.AddField(
            model_name='post',
            name='objetivo',
            field=models.CharField(choices=[('evento', 'Divulgar evento'), ('venda', 'Venda / Promoção'), ('educacional', 'Conteúdo educacional'), ('institucional', 'Institucional / Branding'), ('bastidores', 'Bastidores / Cultura'), ('depoimento', 'Depoimento / Case'), ('datas_comemorativas', 'Datas comemorativas'), ('engajamento', 'Engajamento (enquete, quiz)')], default='institucional', max_length=30, verbose_name='Objetivo do post'),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_image_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chave S3 da imagem raw'),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_image_s3_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL S3 da imagem raw'),
        ),
        migrations.AddField(
            model_name='postreferenceimage',
            name='aspects_to_use',
            field=models.JSONField(blank=True, default=list, help_text='paleta_cor, mood, composicao, tipografia_aplicada, uso_fotografia, estilo_ilustracao, grafismos, tratamento_cor', verbose_name='Aspectos a aproveitar'),
        ),
        migrations.AddField(
            model_name='postreferenceimage',
            name='importance',
            field=models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10, verbose_name='Importância'),
        ),
        migrations.AddField(
            model_name='postreferenceimage',
            name='usage_description',
            field=models.TextField(blank=True, verbose_name='O que aproveitar desta imagem'),
        ),
        migrations.AddField(
            model_name='postreferenceimage',
            name='usage_type',
            field=models.CharField(choices=[('inspire', 'Inspirar'), ('mimic', 'Seguir fielmente'), ('avoid', 'EVITAR')], default='inspire', max_length=10, verbose_name='Tipo de uso'),
        ),
        migrations.CreateModel(
            name='PostGenerationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_used', models.CharField(choices=[('free_style', 'Estilo livre'), ('controlled_render', 'Renderização controlada')], max_length=30, verbose_name='Método utilizado')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='Aprovado')),
                ('revisions_requested', models.PositiveIntegerField(default=0, verbose_name='Revisões solicitadas')),
                ('time_to_approval_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo até aprovação (segundos)')),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Avaliação do usuário (1-5)')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens consumidos')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Custo (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_metrics', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Métrica de Geração de Post',
                'verbose_name_plural': 'Métricas de Geração de Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method_used', '-created_at'], name='posts_postg_method__659455_idx'), models.Index(fields=['post', 'method_used'], name='posts_postg_post_id_688991_idx')],
            },
        ),
    ]
