# Generated by Django 4.2.8 on 2026-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_comparison_image_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pipeline_used',
            field=models.CharField(choices=[('n8n', 'N8N (workflow externo)'), ('local', 'Local (Celery interno)')], default='n8n', help_text='Qual pipeline foi acionado: N8N externo (producao) ou Celery local (homol)', max_length=10, verbose_name='Pipeline usada'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ia_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic')], max_length=20, verbose_name='Provider IA'),
        ),
    ]
