# Generated by Django 4.2.8 on 2026-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0024_knowledgebase_brand_visual_spec_v1_backup_and_more'),
        ('posts', '0014_post_comparison_image_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='execution_plan',
            field=models.JSONField(blank=True, help_text='Output do orquestrador: slots resolvidos para Pillow renderizar', null=True, verbose_name='Plano de execução do Compose Engine'),
        ),
        migrations.AddField(
            model_name='post',
            name='visual_template',
            field=models.ForeignKey(blank=True, help_text='Template escolhido no modal Colletivo (None = fluxo N8N tradicional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_using_template', to='knowledge.visualtemplate', verbose_name='Template visual selecionado'),
        ),
    ]
