# Generated by Django 4.2.8 on 2026-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_add_pipeline_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slides_data',
            field=models.JSONField(blank=True, default=list, help_text='Lista de slides com title/subtitle/image_prompt para carrossel', verbose_name='Slides (carrossel)'),
        ),
        migrations.AddField(
            model_name='post',
            name='visual_brief',
            field=models.TextField(blank=True, default='', help_text='Diretrizes de marca para o gerador de imagem', verbose_name='Visual brief'),
        ),
    ]
