# Generated by Django 4.2.8 on 2026-05-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_add_visual_brief_and_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local_pipeline_context',
            field=models.JSONField(blank=True, default=dict, help_text='Logos/refs selecionados + descricao de uso (somente pipeline local)', verbose_name='Contexto pipeline local'),
        ),
    ]
