# Generated by Django 4.2.8 on 2026-05-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_add_local_pipeline_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_usage_log',
            field=models.JSONField(blank=True, default=list, help_text='Historico granular de cada chamada (Claude/Gemini). Cada entry: {timestamp, step, model, input_tokens, output_tokens, images_generated, cost_usd, cost_brl}', verbose_name='Log de uso de IA'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Soma de todos os custos de IA deste post (multiplas geracoes incluidas)', max_digits=10, verbose_name='Custo total (USD)'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_image_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Acumulado de todas as chamadas de IA para gerar imagem', max_digits=10, verbose_name='Custo total imagem (USD)'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_text_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Acumulado de todas as chamadas de IA para gerar texto', max_digits=10, verbose_name='Custo total texto (USD)'),
        ),
    ]
