# Generated by Django 4.2.8 on 2026-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_add_ai_cost_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='copy_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Output do copywriter: variants, recommended_variant, design_hints, metrics', verbose_name='Payload do copywriter agent'),
        ),
        migrations.AddField(
            model_name='post',
            name='designer_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Output do designer: wireframe_plan, image_prompts, approval, flags', verbose_name='Payload do designer agent'),
        ),
        migrations.AddField(
            model_name='post',
            name='wireframe_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chave S3 do wireframe PNG'),
        ),
        migrations.AddField(
            model_name='post',
            name='wireframe_s3_url',
            field=models.URLField(blank=True, help_text='Preview visual do plano antes do Gemini — base do canvas editavel', max_length=1000, verbose_name='URL S3 do wireframe PNG'),
        ),
    ]
