# Generated by Django 4.2.8 on 2026-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_add_failed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreferenceimage',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('produto', 'Produto (manter fiel ao original)'), ('pessoa', 'Pessoa / Speaker'), ('cenario', 'Cenario / Lugar'), ('referencia_estilo', 'Referencia de estilo'), ('icone', 'Icone / Elemento grafico'), ('fundo', 'Fundo / Textura'), ('outro', 'Outro')], default='', max_length=32, verbose_name='Tipo de uso'),
        ),
    ]
