# Generated by Django 4.2.8 on 2026-06-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0026_brandgraficmodule_analysis_cost_usd_and_more'),
        ('core', '0012_organization_archetype_selector_enabled'),
        ('posts', '0022_alter_postreferenceimage_usage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador do arquétipo (ex.: A, B, B_DUO, C, C_DISPLAY)', max_length=40, verbose_name='Chave')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição')),
                ('format', models.CharField(choices=[('feed', 'Feed 4:5'), ('story', 'Story 9:16'), ('both', 'Feed e Story')], default='feed', max_length=10, verbose_name='Formato')),
                ('spec', models.JSONField(default=dict, help_text='Ficha de layout (zonas, coords, fontes, tratamento) que o renderizador usa', verbose_name='Ficha (spec)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='core.organization', verbose_name='Organização')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.referenceimage', verbose_name='Thumbnail (imagem de referência)')),
            ],
            options={
                'verbose_name': 'Arquétipo de Post',
                'verbose_name_plural': 'Arquétipos de Post',
                'ordering': ['organization', 'order', 'key'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
