# Generated by Django 4.2.8 on 2026-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_postarchetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pipeline_used',
            field=models.CharField(choices=[('n8n', 'N8N (workflow externo)'), ('local', 'Local (Celery interno)'), ('simple', 'Simples (Celery + OpenAI, 1 agente)'), ('todxs', 'TODXS (arquetipos, render deterministico)'), ('vb', 'VB Gastronomia (arquetipos, render deterministico)'), ('samsung', 'Samsung Healthcare (arquetipos, render deterministico)')], default='n8n', help_text='Qual pipeline foi acionado: N8N externo, Celery local ou pipeline de arte da org', max_length=10, verbose_name='Pipeline usada'),
        ),
    ]
