# Generated by Django 4.2.8 on 2026-02-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_populate_plan_templates'),
        ('knowledge', '0017_add_accepted_suggestion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('rede_social', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter')], max_length=20, verbose_name='Rede Social')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('generated', 'Gerado')], default='requested', max_length=20, verbose_name='Status')),
                ('n8n_id', models.IntegerField(blank=True, null=True, verbose_name='ID N8N')),
                ('n8n_data', models.JSONField(blank=True, default=dict, verbose_name='Dados N8N')),
                ('generation_request', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Solicitado em')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Editado em')),
                ('audit_history', models.JSONField(blank=True, default=list, verbose_name='Histórico de Auditoria')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='knowledge.knowledgebase')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_ia', to='core.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='pautas_paut_organiz_9fa0a5_idx'), models.Index(fields=['status', 'rede_social'], name='pautas_paut_status_4fa9fb_idx'), models.Index(fields=['knowledge_base'], name='pautas_paut_knowled_30f32b_idx')],
            },
        ),
    ]
