# Generated by Django 4.2.8 on 2026-02-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_plan_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_marketing_enabled',
            field=models.BooleanField(default=False, help_text='Empresa autorizada a usar módulo de email marketing', verbose_name='Email Marketing Habilitado'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pautas_enabled',
            field=models.BooleanField(default=True, help_text='Empresa autorizada a usar módulo de pautas', verbose_name='Pautas Habilitadas'),
        ),
        migrations.AddField(
            model_name='organization',
            name='posts_enabled',
            field=models.BooleanField(default=True, help_text='Empresa autorizada a usar módulo de posts', verbose_name='Posts Habilitados'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trends_enabled',
            field=models.BooleanField(default=False, help_text='Empresa autorizada a usar módulo de trends', verbose_name='Trends Habilitados'),
        ),
    ]
