# Generated by Django 4.2.7 on 2026-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_videos_avatar_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_image_revisions',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número máximo de alterações de imagem permitidas por post (0 = ilimitado)', verbose_name='Máx. Alterações de Imagem'),
        ),
    ]
