# Generated by Django 4.2.8 on 2026-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_max_image_revisions_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do responsável pela conta (somente dígitos). Usado para cobrança.', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Referência do pagamento (ex: ID do Mercado Pago) que liberou a conta.', max_length=120, verbose_name='Referência de Pagamento'),
        ),
        migrations.AddField(
            model_name='organization',
            name='requested_plan',
            field=models.CharField(blank=True, default='', help_text='Plano escolhido no site no cadastro (aplicado na confirmação de pagamento). Ex: starter, pro', max_length=20, verbose_name='Plano Solicitado'),
        ),
    ]
