# Generated by Django 4.2.8 on 2026-05-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_comparison_image_s3_key_and_more'),
        ('knowledge', '0024_knowledgebase_brand_visual_spec_v1_backup_and_more'),
        ('core', '0009_add_max_image_revisions_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini')], max_length=20, verbose_name='Provider')),
                ('model', models.CharField(help_text='Ex: claude-sonnet-4-5, gpt-4o, gemini-3-pro-image-preview', max_length=100, verbose_name='Modelo')),
                ('purpose', models.CharField(choices=[('analyze_brandguide', 'Brandguide - analise estrutural'), ('analyze_reference_image', 'Referencia - descritivo visual'), ('orchestrate_post', 'Orquestrador - plano de geracao'), ('generate_post_text', 'Post - geracao de texto'), ('generate_post_image', 'Post - geracao de imagem'), ('kb_compilation', 'KB - compilation summary'), ('other', 'Outro')], max_length=40, verbose_name='Proposito')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_usage', models.JSONField(blank=True, default=dict, help_text='Dict bruto do response.usage para debug')),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='knowledge.knowledgebase', verbose_name='KB relacionada')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='core.organization', verbose_name='Organizacao')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='posts.post', verbose_name='Post relacionado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que disparou')),
            ],
            options={
                'verbose_name': 'Log de uso de IA',
                'verbose_name_plural': 'Logs de uso de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='core_aiusag_organiz_10a424_idx'), models.Index(fields=['post', '-created_at'], name='core_aiusag_post_id_e12f5c_idx'), models.Index(fields=['purpose', '-created_at'], name='core_aiusag_purpose_6555bb_idx'), models.Index(fields=['provider', 'model'], name='core_aiusag_provide_a83ee3_idx')],
            },
        ),
    ]
