# Generated by Django 4.2.8 on 2026-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_plan_templates_starter_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archetype_selector_enabled',
            field=models.BooleanField(default=False, help_text="Mostra no modal de gerar post a opção 'Usar template' (escolher arquétipo + cor)", verbose_name='Seletor de Arquétipo Habilitado'),
        ),
    ]
