# Generated by Django 4.2.8 on 2026-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organization_archetype_selector_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archetype_engine_v3',
            field=models.BooleanField(default=False, help_text='Renderiza os arquétipos desta org pelo ENGINE V3 (motor único, spec convertida on-the-fly). Desligar = volta instantâneo ao pipeline dedicado. Rollout org a org.', verbose_name='Engine V3 de Arquétipos'),
        ),
    ]
