# Generated by Django 4.2.8 on 2026-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_archetype_engine_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='advanced_editor_enabled',
            field=models.BooleanField(default=False, help_text='Mostra o botão "Edição Avançada" (editor de arte) para os usuários desta empresa. A equipe interna (staff/superuser) sempre vê, independente desta flag.', verbose_name='Edição Avançada Habilitada'),
        ),
    ]
