# Generated by Django 4.2.8 on 2026-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_post_pipeline_used'),
        ('core', '0014_organization_advanced_editor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Ex.: 'posts', 'knowledge', 'brand_layout'", max_length=30, verbose_name='Origem')),
                ('pipeline', models.CharField(blank=True, help_text='pipeline_used do post no momento do evento (quando houver)', max_length=20, verbose_name='Pipeline')),
                ('step', models.CharField(max_length=40, verbose_name='Etapa')),
                ('purpose', models.CharField(blank=True, max_length=80, verbose_name='Propósito')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveIntegerField(default=0)),
                ('images_generated', models.PositiveSmallIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_brl', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_events', to='core.organization', verbose_name='Organização')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Evento de Uso de IA',
                'verbose_name_plural': 'Eventos de Uso de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='core_aiusag_organiz_3bfcd3_idx'), models.Index(fields=['organization', 'source', '-created_at'], name='core_aiusag_organiz_917f38_idx')],
            },
        ),
    ]
