# Generated by Django 4.2.8 on 2026-07-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aiusageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archetype_two_step',
            field=models.BooleanField(default=False, help_text='Pipelines de arquétipo em DUAS ETAPAS: o brain gera os textos + descrição da imagem e o post para em "pending" (portão de aprovação, como no fluxo simples); só depois da aprovação roda Gemini + render. Desligar = etapa única (comportamento atual). Rollout org a org.', verbose_name='Arquétipos em Duas Etapas'),
        ),
    ]
